-- ORVANN Gestión — Seed de diseños (referencias culturales)
-- Extraído de la hoja Resumen del Google Sheet original (Control_Operativo_Orvann).
-- Se ejecuta después del schema principal, en Supabase SQL Editor.

insert into disenos (nombre, categoria, referencia_ano, descripcion, activo) values
  ('Pulp Fiction', 'cine', 1994, 'Película de Quentin Tarantino', false),
  ('Pedro Navaja', 'musica', 1978, 'Salsa narrativa, Rubén Blades', false),
  ('Léon: The Professional', 'cine', 1994, 'Película de Luc Besson', false),
  ('Ciudad de Dios', 'cine', 2002, 'Película brasileña, Fernando Meirelles', false),
  ('Charles Bukowski', 'literatura', null, 'Literatura cruda, poeta maldito', false),
  ('Héctor Lavoe - Vinyl Cover', 'musica', null, 'Salsa, estilo portada de vinilo', false),
  ('Gabo - Cien Años de Soledad', 'literatura', 1967, 'García Márquez', false),
  ('Blade Runner', 'cine', 1982, 'Ridley Scott, neo-noir cyberpunk', false),
  ('Mercedes Sosa - Volver a los 17', 'musica', null, 'Mercedes Sosa con La Fania', false),
  ('Taxi Driver', 'cine', 1976, 'Scorsese, De Niro', false),
  ('Fight Club', 'cine', 1999, 'Fincher, Pitt/Norton', false),
  ('Scarface', 'cine', 1983, 'De Palma, Al Pacino', false),
  ('Vendedora de Rosas', 'cine', 1998, 'Víctor Gaviria, Medellín', false),
  ('Notorious BIG', 'musica', null, 'Hip hop, East Coast', false),
  ('Celia Cruz', 'musica', null, 'Reina de la salsa', false),
  ('Mike Tyson', 'deporte', null, 'Boxeo', false),
  ('Príncipe de Bel Air', 'tv', 1990, 'Sitcom, Will Smith', false),
  ('Jackass', 'tv', 2000, 'MTV, cultura skate', false),
  ('Friends', 'tv', 1994, 'Sitcom icónico', false),
  ('MTV', 'cultura_pop', null, 'Estética de los 90', false),
  ('PlayStation 1', 'cultura_pop', 1994, 'Nostalgia gaming', false),
  ('Backstreet Boys', 'musica', null, 'Boy band 90s', false),
  ('Punk', 'musica', null, 'Estética punk rock', false),
  ('Eminem', 'musica', null, 'Rap, Slim Shady era', false),
  ('Tupac y BIG', 'musica', null, 'Hip hop, East vs West', false),
  ('Cerati y Rock Español', 'musica', null, 'Soda Stereo, Cadillacs, Caifanes', false),
  ('Mi Pobre Angelito', 'cine', 1990, 'Home Alone, clásico navideño', false),
  ('Manos de Tijera', 'cine', 1990, 'Edward Scissorhands, Burton', false),
  ('Titanic', 'cine', 1997, 'Cameron, DiCaprio/Winslet', false),
  ('Sexto Sentido', 'cine', 1999, 'Shyamalan', false),
  ('Marc Anthony', 'musica', null, 'Salsa romántica', false),
  ('Grupo Niche', 'musica', null, 'Salsa colombiana', false),
  ('Gran Combo de las Estrellas', 'musica', null, 'Salsa clásica', false),
  ('Rocky', 'cine', 1976, 'Stallone, boxeo', false),
  ('Canserbero', 'musica', null, 'Rap venezolano, canon', false),
  ('Thalía', 'musica', null, 'Pop latino 90s', false),
  ('Vicente Fernández', 'musica', null, 'Ranchera, El Charro', false),
  ('El Principito', 'literatura', 1943, 'Saint-Exupéry', false),
  ('La Máscara / Show de Truman', 'cine', null, 'Jim Carrey, doble referencia', false);
